APP_NAME = "GT&D Intelligence Platform"
APP_VERSION = "1.0.0"

DEFAULT_POWER_FACTOR = 0.90
DEFAULT_TRANSFORMER_MVA = 100.0
DEFAULT_PRIMARY_KV = 230.0
DEFAULT_SECONDARY_KV = 33.0

WARNING_LOADING_PCT = 80.0
CRITICAL_LOADING_PCT = 100.0

WARNING_TEMP_C = 75.0
CRITICAL_TEMP_C = 90.0

DB_PATH = "database/gtd.db"
